---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-symlinks
          - id: check-shebang-scripts-are-executable
          - id: detect-private-key

    - repo: https://github.com/rhysd/actionlint
      rev: v1.7.7
      hooks:
          - id: actionlint-docker

    - repo: https://github.com/renovatebot/pre-commit-hooks
      rev: 41.61.1
      hooks:
          - id: renovate-config-validator
            args: [--strict]
            # TODO : revert this when https://github.com/renovatebot/pre-commit-hooks/issues/2460 is fixed
            language_version: lts

    - repo: https://github.com/compilerla/conventional-pre-commit
      rev: v4.2.0
      hooks:
          - id: conventional-pre-commit
            stages: [commit-msg]
            args: [--strict, --force-scope]

    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.10.0.1 # use tags until renovate supports sha: https://github.com/renovatebot/renovate/issues/22567
      hooks:
          - id: shellcheck

    - repo: https://github.com/adrienverge/yamllint
      rev: v1.37.1
      hooks:
          - id: yamllint
            args: [-c, .yamllint.yaml]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
